server:
  port: 8881
spring:
  application:
    name: commonservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JiaoHongwei/Spring-Cloud-Config.git
          search-paths: user
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/