server:
  port: 8090
spring:
  application:
    name: businessservice-user-client-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: info
    org.springframework.web.servlet.DspatcherServlet: debug
    org.springframework.cloud.sleuth: debug