eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8882
  #  rabbitmq
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq-qm
    password: 8zoYBxdV

  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh