server:
  port: 8091
spring:
  application:
    name: businessservice-user-client-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    # 打开断路器功能
    enabled: true
logging:
  level:
    root: info
    org.springframework.cloud.sleuth: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"